name: Test HTML
on: [push, pull_request]

jobs:
  Deploy-To-Sinners:
    name: Test HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Validate HTML5
        uses: Cyb3r-Jak3/html5validator-action@v0.3
        with:
          root: '${{env.LOCAL_DIR}}/'
